In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\vipul\Downloads\ecommerce_dirty_raw_dataset.csv")
df

,Order_ID,Customer_ID,Customer_Name,City,Order_Date,Product_ID,Product_Name,Category,Quantity,Unit_Price,Discount,Payment_Method,Order_Status,Total_Amount
0,ORD0001,C007,Rohan Kumar,Pune,17-04-2026,P104,Power Bank,Electronics,1.0,1299,10,Cash on Delivery,Cancelled,1169.10
1,ORD0002,C005,Arjun Mehta,Mumbai,03-08-2026,P107,Desk Lamp,Home & Kitchen,2.0,999,10,Debit Card,Delivered,1798.20
2,ORD0003,C008,Ananya Jain,Chandigarh,01-06-2026,P105,Backpack,Bags,4.0,1499,15,Debit Card,Cancelled,5096.60
3,ORD0004,C002,Priya Verma,Gurugram,11-07-2026,P108,Notebook,Stationery,4.0,199,5,Cash on Delivery,Cancelled,756.20
4,ORD0005,C001,Aarav Sharma,Delhi,24-08-2026,P110,Phone Stand,Accessories,2.0,399,0,UPI,Delivered,798.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,ORD0009,C010,Isha Malhotra,Gurugram,02-04-2026,P109,Headphones,Electronics,2.0,1799,0,Debit Card,Pending,3598.00
121,ORD0028,C009,Vikas Yadav,Delhi,17-05-2026,P103,USB-C Cable,Accessories,3.0,349,5,Credit Card,Cancelled,994.65
122,ORD0073,C004,Neha Gupta,Jaipur,06-08-2026,P105,Backpack,Bags,4.0,1499,15,Credit Card,Cancelled,5096.60
123,ORD0102,C012,Meera Joshi,Lucknow,01-08-2026,P105,Backpack,Bags,4.0,1499,5,Debit Card,Pending,5696.20
124,ORD0004,C002,Priya Verma,Gurugram,11-07-2026,P108,Notebook,Stationery,4.0,199,5,Cash on Delivery,Cancelled,756.20

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        124 non-null    str
 1   Customer_ID     124 non-null    str
 2   Customer_Name   124 non-null    str
 3   City            125 non-null    str
 4   Order_Date      125 non-null    str
 5   Product_ID      125 non-null    str
 6   Product_Name    125 non-null    str
 7   Category        125 non-null    str
 8   Quantity        124 non-null    float64
 9   Unit_Price      124 non-null    str
 10  Discount        125 non-null    int64
 11  Payment_Method  125 non-null    str
 12  Order_Status    125 non-null    str
 13  Total_Amount    125 non-null    float64
dtypes: float64(2), int64(1), str(11)
memory usage: 13.8 KB

In [4]:
df.columns

Index(['Order_ID', 'Customer_ID', 'Customer_Name', 'City', 'Order_Date',
       'Product_ID', 'Product_Name', 'Category', 'Quantity', 'Unit_Price',
       'Discount', 'Payment_Method', 'Order_Status', 'Total_Amount'],
      dtype='str')

In [5]:
df.head()

,Order_ID,Customer_ID,Customer_Name,City,Order_Date,Product_ID,Product_Name,Category,Quantity,Unit_Price,Discount,Payment_Method,Order_Status,Total_Amount
0,ORD0001,C007,Rohan Kumar,Pune,17-04-2026,P104,Power Bank,Electronics,1.0,1299,10,Cash on Delivery,Cancelled,1169.1
1,ORD0002,C005,Arjun Mehta,Mumbai,03-08-2026,P107,Desk Lamp,Home & Kitchen,2.0,999,10,Debit Card,Delivered,1798.2
2,ORD0003,C008,Ananya Jain,Chandigarh,01-06-2026,P105,Backpack,Bags,4.0,1499,15,Debit Card,Cancelled,5096.6
3,ORD0004,C002,Priya Verma,Gurugram,11-07-2026,P108,Notebook,Stationery,4.0,199,5,Cash on Delivery,Cancelled,756.2
4,ORD0005,C001,Aarav Sharma,Delhi,24-08-2026,P110,Phone Stand,Accessories,2.0,399,0,UPI,Delivered,798.0

In [6]:
df.tail()

,Order_ID,Customer_ID,Customer_Name,City,Order_Date,Product_ID,Product_Name,Category,Quantity,Unit_Price,Discount,Payment_Method,Order_Status,Total_Amount
120,ORD0009,C010,Isha Malhotra,Gurugram,02-04-2026,P109,Headphones,Electronics,2.0,1799,0,Debit Card,Pending,3598.00
121,ORD0028,C009,Vikas Yadav,Delhi,17-05-2026,P103,USB-C Cable,Accessories,3.0,349,5,Credit Card,Cancelled,994.65
122,ORD0073,C004,Neha Gupta,Jaipur,06-08-2026,P105,Backpack,Bags,4.0,1499,15,Credit Card,Cancelled,5096.60
123,ORD0102,C012,Meera Joshi,Lucknow,01-08-2026,P105,Backpack,Bags,4.0,1499,5,Debit Card,Pending,5696.20
124,ORD0004,C002,Priya Verma,Gurugram,11-07-2026,P108,Notebook,Stationery,4.0,199,5,Cash on Delivery,Cancelled,756.20

In [7]:
df.shape

(125, 14)

In [8]:
df.describe(include='all')

,Order_ID,Customer_ID,Customer_Name,City,Order_Date,Product_ID,Product_Name,Category,Quantity,Unit_Price,Discount,Payment_Method,Order_Status,Total_Amount
count,124,124,124,125,125,125,125,125,124.000000,124,125.000000,125,125,125.000000
unique,119,12,12,11,99,10,11,6,NaN,11,NaN,6,4,NaN
top,ORD0004,C001,Aarav Sharma,Delhi,05-08-2026,P107,Desk Lamp,Electronics,NaN,999,NaN,Cash on Delivery,Delivered,NaN
freq,2,15,15,26,4,19,19,46,NaN,18,NaN,36,65,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.556452,NaN,9.560000,NaN,NaN,2940.664000
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.225093,NaN,10.663776,NaN,NaN,8916.006761
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.000000,NaN,0.000000,NaN,NaN,169.150000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.750000,NaN,5.000000,NaN,NaN,849.150000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.000000,NaN,10.000000,NaN,NaN,1619.100000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.000000,NaN,15.000000,NaN,NaN,3396.600000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.000000,NaN,110.000000,NaN,NaN,99999.000000

In [9]:
df.isnull().sum()

Order_ID          1
Customer_ID       1
Customer_Name     1
City              0
Order_Date        0
Product_ID        0
Product_Name      0
Category          0
Quantity          1
Unit_Price        1
Discount          0
Payment_Method    0
Order_Status      0
Total_Amount      0
dtype: int64

In [10]:
df.isna().sum()

Order_ID          1
Customer_ID       1
Customer_Name     1
City              0
Order_Date        0
Product_ID        0
Product_Name      0
Category          0
Quantity          1
Unit_Price        1
Discount          0
Payment_Method    0
Order_Status      0
Total_Amount      0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(5)

In [12]:
df.nunique()

Order_ID          119
Customer_ID        12
Customer_Name      12
City               11
Order_Date         99
Product_ID         10
Product_Name       11
Category            6
Quantity            5
Unit_Price         11
Discount            5
Payment_Method      6
Order_Status        4
Total_Amount       82
dtype: int64

In [13]:
for col in ['City','Category','Payment_Method','Order_Status','Product_Name']:
    print(col,df[col].unique(),'\n')

City <StringArray>
[      'Pune',     'Mumbai', 'Chandigarh',   'Gurugram',      'Delhi',
      'Noida',    'Lucknow',   'gurugram',   'GURUGRAM',     'Jaipur',
  'Bengaluru']
Length: 11, dtype: str

Category <StringArray>
[   'Electronics', 'Home & Kitchen',           'Bags',     'Stationery',
    'Accessories',   'electronics ']
Length: 6, dtype: str

Payment_Method <StringArray>
['Cash on Delivery', 'Debit Card', 'UPI', 'Credit Card', 'upi', 'Credit card']
Length: 6, dtype: str

Order_Status <StringArray>
['Cancelled', 'Delivered', 'Pending', 'delivered']
Length: 4, dtype: str

Product_Name <StringArray>
[      'Power Bank',        'Desk Lamp',         'Backpack',
         'Notebook',      'Phone Stand',       'Headphones',
         'Keyboard',   'Wireless Mouse',      'USB-C Cable',
     'Water Bottle', ' Wireless Mouse ']
Length: 11, dtype: str

In [15]:
for c in ["Customer_Name", "City", "Product_Name", "Category", "Order_Status", "Payment_Method"]:
    df[c] = df[c].str.strip().str.title()
df["Payment_Method"] = df["Payment_Method"].replace({"Upi": "UPI"})
df

,Order_ID,Customer_ID,Customer_Name,City,Order_Date,Product_ID,Product_Name,Category,Quantity,Unit_Price,Discount,Payment_Method,Order_Status,Total_Amount
0,ORD0001,C007,Rohan Kumar,Pune,17-04-2026,P104,Power Bank,Electronics,1.0,1299,10,Cash On Delivery,Cancelled,1169.10
1,ORD0002,C005,Arjun Mehta,Mumbai,03-08-2026,P107,Desk Lamp,Home & Kitchen,2.0,999,10,Debit Card,Delivered,1798.20
2,ORD0003,C008,Ananya Jain,Chandigarh,01-06-2026,P105,Backpack,Bags,4.0,1499,15,Debit Card,Cancelled,5096.60
3,ORD0004,C002,Priya Verma,Gurugram,11-07-2026,P108,Notebook,Stationery,4.0,199,5,Cash On Delivery,Cancelled,756.20
4,ORD0005,C001,Aarav Sharma,Delhi,24-08-2026,P110,Phone Stand,Accessories,2.0,399,0,UPI,Delivered,798.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,ORD0009,C010,Isha Malhotra,Gurugram,02-04-2026,P109,Headphones,Electronics,2.0,1799,0,Debit Card,Pending,3598.00
121,ORD0028,C009,Vikas Yadav,Delhi,17-05-2026,P103,Usb-C Cable,Accessories,3.0,349,5,Credit Card,Cancelled,994.65
122,ORD0073,C004,Neha Gupta,Jaipur,06-08-2026,P105,Backpack,Bags,4.0,1499,15,Credit Card,Cancelled,5096.60
123,ORD0102,C012,Meera Joshi,Lucknow,01-08-2026,P105,Backpack,Bags,4.0,1499,5,Debit Card,Pending,5696.20
124,ORD0004,C002,Priya Verma,Gurugram,11-07-2026,P108,Notebook,Stationery,4.0,199,5,Cash On Delivery,Cancelled,756.20

In [22]:
df = df.drop_duplicates().dropna(subset=["Order_ID", "Customer_ID"]).reset_index(drop=True)
df

,Order_ID,Customer_ID,Customer_Name,City,Order_Date,Product_ID,Product_Name,Category,Quantity,Unit_Price,Discount,Payment_Method,Order_Status,Total_Amount
0,ORD0001,C007,Rohan Kumar,Pune,2026-04-17,P104,Power Bank,Electronics,1.0,1299.0,10,Cash On Delivery,Cancelled,1169.1
1,ORD0002,C005,Arjun Mehta,Mumbai,2026-08-03,P107,Desk Lamp,Home & Kitchen,2.0,999.0,10,Debit Card,Delivered,1798.2
2,ORD0003,C008,Ananya Jain,Chandigarh,2026-06-01,P105,Backpack,Bags,4.0,1499.0,15,Debit Card,Cancelled,5096.6
3,ORD0004,C002,Priya Verma,Gurugram,2026-07-11,P108,Notebook,Stationery,4.0,199.0,5,Cash On Delivery,Cancelled,756.2
4,ORD0005,C001,Aarav Sharma,Delhi,2026-08-24,P110,Phone Stand,Accessories,2.0,399.0,0,UPI,Delivered,798.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113,ORD0115,C005,Arjun Mehta,Mumbai,2026-01-23,P105,Backpack,Bags,2.0,1499.0,10,UPI,Cancelled,2698.2
114,ORD0117,C001,Aarav Sharma,Delhi,2026-09-17,P103,Usb-C Cable,Accessories,1.0,349.0,0,Credit Card,Delivered,349.0
115,ORD0118,C001,Aarav Sharma,Delhi,2026-04-05,P108,Notebook,Stationery,4.0,199.0,5,Cash On Delivery,Delivered,756.2
116,ORD0119,C010,Isha Malhotra,Gurugram,2026-09-16,P102,Keyboard,Electronics,2.0,899.0,5,Debit Card,Delivered,1708.1
117,ORD0120,C012,Meera Joshi,Lucknow,2026-08-10,P101,Wireless Mouse,Electronics,2.0,599.0,15,Debit Card,Delivered,1018.3

In [23]:
df["Customer_Name"] = df["Customer_Name"].fillna(df.groupby("Customer_ID")["Customer_Name"].transform("first"))
df["Unit_Price"] = df["Unit_Price"].fillna(df.groupby("Product_ID")["Unit_Price"].transform("median"))
df["Quantity"] = df["Quantity"].fillna(df["Quantity"].mode()[0]).astype(int)

In [24]:
df.info()
print("Missing:", df.isna().sum().sum(), "| Duplicates:", df.duplicated().sum())

<class 'pandas.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        118 non-null    str
 1   Customer_ID     118 non-null    str
 2   Customer_Name   118 non-null    str
 3   City            118 non-null    str
 4   Order_Date      116 non-null    datetime64[us]
 5   Product_ID      118 non-null    str
 6   Product_Name    118 non-null    str
 7   Category        118 non-null    str
 8   Quantity        118 non-null    int64
 9   Unit_Price      118 non-null    float64
 10  Discount        118 non-null    int64
 11  Payment_Method  118 non-null    str
 12  Order_Status    118 non-null    str
 13  Total_Amount    118 non-null    float64
dtypes: datetime64[us](1), float64(2), int64(2), str(9)
memory usage: 13.0 KB
Missing: 2 | Duplicates: 0

In [25]:
df[df['Order_Date'].isna()]

,Order_ID,Customer_ID,Customer_Name,City,Order_Date,Product_ID,Product_Name,Category,Quantity,Unit_Price,Discount,Payment_Method,Order_Status,Total_Amount
76,ORD0077,C004,Neha Gupta,Jaipur,NaT,P108,Notebook,Stationery,4,199.0,10,UPI,Pending,716.4
83,ORD0084,C008,Ananya Jain,Chandigarh,NaT,P104,Power Bank,Electronics,1,1299.0,0,Cash On Delivery,Delivered,1299.0

In [27]:
df = df.dropna(subset=['Order_Date']).reset_index(drop=True)

In [28]:
df["Calc_Total"] = (df["Quantity"] * df["Unit_Price"] * (1 - df["Discount"] / 100)).round(2)
print("Total_Amount mismatches:", (df["Calc_Total"] != df["Total_Amount"].round(2)).sum())

Total_Amount mismatches: 3

In [29]:
df = df.drop(columns="Calc_Total")

print("Shape:", df.shape)
print("Missing:", df.isna().sum().sum(), "| Duplicates:", df.duplicated().sum())

df.to_csv("cleaned_data.csv", index=False)

Shape: (116, 14)
Missing: 0 | Duplicates: 0